version: "3"

services:
  app:
    image: nginx
    env_file: .env
    volumes:
      - ${SHARE_PATH:-./data}:/usr/share/nginx/html:ro
      - ./nginx/conf.d/autoindex.conf:/etc/nginx/conf.d/autoindex.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_overlay"

      - "traefik.http.services.web-share.loadbalancer.server.port=80"

      - "traefik.http.routers.web-share-http.entrypoints=web"
      - "traefik.http.routers.web-share-http.rule=Host(`${DOMAIN:-web-share.localhost}`)"
    networks:
      - default
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_overlay
